musl compat
multipath-tcp/mptcpd pull request #314
Opened 2024-11-20 15:17 UTC by matttbe

Here are a few small patches needed to be able to compile mptcpd with musl, e.g. on AlpineLinux

2025-01-24 15:51 UTC, matttbe commented
FYI, these 4 patches have been included in Alpine

2025-01-24 15:53 UTC, matttbe commented
FYI, these 4 patches have been [included](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/75529) in the new AlpineLinux [packages](https://pkgs.alpinelinux.org/packages?name=mptcp*).

2025-01-27 12:35 UTC, ossama-othman requested changes

2025-01-27 14:57 UTC, matttbe commented on src/configuration.c
> +#if MPTCPD_LOGGER == stderr
Arf, of course, good point. I will do the comparison elsewhere :)

2025-01-27 16:41 UTC, matttbe commented
@ossama-othman Thank you for the different reviews! I applied the requested modifications (and rebased on top of `main`).

2025-04-29 10:07 UTC, matttbe commented
@ossama-othman by chance, do you have the opportunity to look at the last version please? :)

I just did a rebase on top of `main`, no other changes have been done. To see the differences with the original version, please see [this](https://github.com/multipath-tcp/mptcpd/compare/e8b9900a1571721e2503442bfea8d73b673940c8..9d8da3ee1ad6f31f0498b42ca58375a7ed612537).

2025-04-30 11:12 UTC, ossama-othman commented on src/mptcpize.c
> +#endif
musl provides the [`err()`](https://git.musl-libc.org/cgit/musl/tree/src/legacy/err.c) function with the same parameter list and behavior. It is defined in [<err.h>](https://git.musl-libc.org/cgit/musl/tree/include/err.h). I think we should fall back on `err()` for musl instead, but I'm not adamant about that. Thoughts?

2025-04-30 11:18 UTC, ossama-othman commented
Sorry for the delay, @matttbe. Let me know what you think about implementing `error()` in terms of musl's `err()`. It's not a blocker for me, so I'm okay approving as is if you prefer.

2025-04-30 11:21 UTC, matttbe commented on src/mptcpize.c
> +#endif
@ossama-othman I didn't know about `err()`, thank you for the tip. I will look at that, looks better and easier.

2025-04-30 11:21 UTC, ossama-othman approved these changes

2025-04-30 11:32 UTC, matttbe commented on src/mptcpize.c
> +#endif
@ossama-othman mmh, it doesn't help that much: `err()` takes the global `errno`, but `error()` is not always used with `errno`. To keep the same message, it looks like we still need to use `perror()`.

Should we keep that like that? Or calling `errno = errnum; err(status, format, __VA_ARGS__)`?

2025-04-30 12:09 UTC, matttbe commented
> Sorry for the delay, @matttbe. Let me know what you think about implementing `error()` in terms of musl's `err()`. It's not a blocker for me, so I'm okay approving as is if you prefer.

No problem, I understand :)

`err()` is also available in glibc, but not acting like `error()`. Either we use `err()` and accept the fact the messages might be less accurate. Or set `errno` and call `err()`, or use the current version. Please let me know what you prefer :)

2025-04-30 12:14 UTC, matttbe commented on src/mptcpize.c
> +#endif
> Or calling `errno = errnum; err(status, format, __VA_ARGS__)`?

Mmh, that's not enough: if we call `err(0, ...)`, it will add `: Success` :)
Or maybe we don't need to care?

2025-05-08 09:43 UTC, matttbe commented
I suggest merging it as it is: defining `error()` is just a few lines of simple code, and `err()` has a different behaviour, we would still need something similar as what has been suggested to imitate `error()`.

Of course, I (or anybody else) can implement something better later :)

2025-05-08 09:44 UTC, merged

2025-05-08 13:07 UTC, ossama-othman commented
Thanks @matttbe!